name: gcp-cicd

on:
  push:
    branches:
      - main

env: 
    GCP_PROJECT_ID: arboreal-cosmos-440011-r8
    GCP_ARTIFACT_REGISTRY: asia-southeast2-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/gcp-hellowow

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Configure Docker for Artifact Registry
        run: |
             gcloud auth configure-docker asia-southeast2-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          docker build -t $GCP_ARTIFACT_REGISTRY/hellowow:latest .
          docker push $GCP_ARTIFACT_REGISTRY/hellowow:latest

  deploy-cloud-run:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: hello-api
          image: $GCP_ARTIFACT_REGISTRY/hellowow:latest
          region: asia-southeast2
#          allow-unauthenticated: false

